# Generated by Django 4.1.2 on 2023-01-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/perfil'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('followers', models.ManyToManyField(related_name='following', to='accounts.user')),
                ('following', models.ManyToManyField(related_name='followers', to='accounts.user')),
            ],
        ),
    ]
