# Generated by Django 4.1.2 on 2023-02-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_of_use',
            field=models.BooleanField(default=True),
        ),
    ]
