#: import audio_player plyer.audio

<Test>
    AudioInterface:
    # text_input: text_input

    # BoxLayout:
    #     orientation: 'vertical'
    #     BoxLayout:
    #         size_hint_y: None
    #         height: 30
    #         Button:
    #             text: 'Load'
    #             on_release: root.open_file_chooser()
    #         Button:
    #             text: 'Save'
    #             on_release: root.show_save()

    #     BoxLayout:
    #         TextInput:
    #             id: text_input
    #             text: ''

    #         RstDocument:
    #             text: text_input.text
    #             show_errors: True



<AudioInterface>:
    audio: audio_player
    orientation: "vertical"

    MDLabel:
        id: state
        text: "Audio is:"+str(root.audio.state)

    MDLabel:
        id: audio_location
        text: "Audio is saved at - "+str(root.audio.file_path)

    MDRectangleFlatButton:
        id: record_button
        text: "RECORD"
        on_release: root.start_recording()


    MDRectangleFlatButton:
        id: play_button
        text: "PLAY"
        on_release: root.start_playing()


<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser
            path: "."

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                id: test
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)

<SaveDialog>:
    text_input: text_input
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser
            on_selection: text_input.text = self.selection and self.selection[0] or ''

        TextInput:
            id: text_input
            size_hint_y: None
            height: 30
            multiline: False

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Save"
                on_release: root.save(filechooser.path, text_input.text)
