# Generated by Django 4.1.2 on 2022-12-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='annotation',
            name='preview',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
