# Generated by Django 4.1.2 on 2022-12-25 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_message'),
        ('core', '0002_alter_annotation_options_annotation_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
