# Generated by Django 4.1.2 on 2023-01-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_reports_report_remove_like_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='images/annotations'),
        ),
    ]
