# Generated by Django 4.1.2 on 2023-01-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_annotation_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
