# Generated by Django 4.1.2 on 2023-02-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_favorite_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.annotation'),
        ),
    ]
