# Generated by Django 4.1.2 on 2023-03-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_report_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/annotations'),
        ),
    ]
