# Generated by Django 4.1.2 on 2023-03-29 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_annotation_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/annotations')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.annotation')),
            ],
        ),
    ]
