# Generated by Django 4.1.2 on 2023-04-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_annotationimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotationimage',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='annotationimage',
            name='id',
        ),
        migrations.AddField(
            model_name='annotationimage',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/annotations'),
        ),
        migrations.AddField(
            model_name='annotationimage',
            name='image3',
            field=models.ImageField(null=True, upload_to='images/annotations'),
        ),
        migrations.AlterField(
            model_name='annotationimage',
            name='annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.annotation'),
        ),
    ]
