# Generated by Django 4.1.2 on 2023-07-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_image_annotationimage_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='encript',
            field=models.BooleanField(default=False),
        ),
    ]
